### ISSUE TITLE
Cannot reshape array

### ISSUE THREAD

**Issue by KilluaZoldich** [neobundy/MLX-Stable-Diffusion-WebUI#1]
100%|█████████████████████████████████████████████████████████████████| 20/20 [00:19<00:00,  1.03it/s]
100%|███████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.10s/it]
2023-12-26 00:23:43.128 Uncaught app exception
Traceback (most recent call last):
  File "/Users/miniconda3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/Volumes/SSD/AI/MLX-APPLE/MLX-Stable-Diffusion-WebUI/main.py", line 65, in <module>
    x = x.reshape(n_rows, B // n_rows, H, W, C).transpose(0, 2, 1, 3, 4)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Cannot reshape array of size 836352 into shape (2,0,528,528,3).

**Comment by neobundy** [comment]
The error is due to the fact that the number of images (`n_images`) you set is not divisible by the number of rows (`n_rows`): n_images=3, n_rows=2, for example. 

I modified the code to handle such cases by padding the grid with empty images:

    # If n_images is not a multiple of n_rows, pad the decoded list with empty images
    if n_images % n_rows != 0:
        for _ in range(n_rows - (n_images % n_rows)):
            decoded.append(mx.zeros_like(decoded[0]))
